import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "yoga-mat",
    name: "FlexiWell Pro Yoga Mat",
    slug: "flexiwell-pro-yoga-mat",
    description:
      "Premium non-slip yoga mat with alignment lines. Extra thick 6mm cushioning provides joint protection during floor exercises. Made with eco-friendly TPE material.",
    shortDescription: "Premium 6mm non-slip mat with alignment lines",
    price: 49.99,
    compareAtPrice: 69.99,
    sku: "FW-MAT-001",
    image:
      "https://images.unsplash.com/photo-1763004871583-4183d64096b1?w=600&h=600&fit=crop",
    category: "equipment",
    inStock: true,
    badge: "Best Seller",
    weight: 48,
    rating: 4.9,
    reviewCount: 247,
  },
  {
    id: "resistance-bands",
    name: "Resistance Bands Set",
    slug: "resistance-bands-set",
    description:
      "Set of 5 color-coded resistance bands (light to extra heavy). Perfect for Pilates, strength training, and rehabilitation exercises. Includes carrying pouch.",
    shortDescription: "5-piece set from light to extra heavy",
    price: 24.99,
    sku: "FW-BAND-001",
    image:
      "https://images.unsplash.com/photo-1584827386916-b5351d3ba34b?w=600&h=600&fit=crop",
    category: "accessories",
    inStock: true,
    weight: 16,
    rating: 4.8,
    reviewCount: 183,
  },
  {
    id: "foam-roller",
    name: "Foam Roller",
    slug: "foam-roller",
    description:
      "High-density EVA foam roller for myofascial release and muscle recovery. Textured surface for deep tissue massage. 18 inches long.",
    shortDescription: 'High-density 18" roller for recovery',
    price: 34.99,
    sku: "FW-ROLL-001",
    image:
      "https://plus.unsplash.com/premium_photo-1661963553074-243e05f053ca?w=600&h=600&fit=crop",
    category: "equipment",
    inStock: true,
    badge: "New",
    weight: 24,
    rating: 4.7,
    reviewCount: 64,
  },
  {
    id: "water-bottle",
    name: "Water Bottle",
    slug: "water-bottle",
    description:
      "Insulated stainless steel water bottle. Keeps drinks cold for 24h or hot for 12h. BPA-free, leak-proof lid. 24oz capacity.",
    shortDescription: "24oz insulated stainless steel",
    price: 22.99,
    sku: "FW-BTL-001",
    image:
      "https://images.unsplash.com/photo-1605714312496-01e90cb509cc?w=600&h=600&fit=crop",
    category: "accessories",
    inStock: true,
    weight: 14,
    rating: 4.6,
    reviewCount: 92,
  },
  {
    id: "reformer-straps",
    name: "Reformer Straps",
    slug: "reformer-straps",
    description:
      "Replacement Pilates reformer straps with padded handles. Compatible with most reformer models. Adjustable length for all body types.",
    shortDescription: "Padded replacement straps, universal fit",
    price: 39.99,
    sku: "FW-STRAP-001",
    image:
      "https://images.unsplash.com/photo-1754258166811-5a09a47800b4?w=600&h=600&fit=crop",
    category: "equipment",
    inStock: true,
    weight: 12,
    rating: 4.8,
    reviewCount: 56,
  },
  {
    id: "workout-towel",
    name: "Workout Towel",
    slug: "workout-towel",
    description:
      "Ultra-absorbent microfiber workout towel. Quick-dry technology, antibacterial treatment. Perfect size for yoga and Pilates classes.",
    shortDescription: "Quick-dry microfiber, antibacterial",
    price: 18.99,
    compareAtPrice: 24.99,
    sku: "FW-TWL-001",
    image:
      "https://images.unsplash.com/photo-1684248655527-46bee8e79029?w=600&h=600&fit=crop",
    category: "apparel",
    inStock: true,
    badge: "Sale",
    weight: 6,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "yoga-blocks",
    name: "Yoga Blocks (Set of 2)",
    slug: "yoga-blocks-set",
    description:
      "Premium cork yoga blocks for stability and alignment. High-density natural cork provides firm support. Rounded edges for comfortable grip. Perfect for all levels.",
    shortDescription: "Natural cork, firm support, rounded edges",
    price: 29.99,
    sku: "FW-BLK-001",
    image:
      "https://images.unsplash.com/photo-1646239646963-b0b9be56d6b5?w=600&h=600&fit=crop",
    category: "equipment",
    inStock: true,
    badge: "New",
    weight: 32,
    rating: 4.9,
    reviewCount: 41,
  },
  {
    id: "stability-ball",
    name: "Stability Ball",
    slug: "stability-ball",
    description:
      "Anti-burst stability ball for core training and Pilates. Includes hand pump. Available in 55cm size, suitable for 5'1\" to 5'7\" height. Textured surface prevents slipping.",
    shortDescription: "55cm anti-burst with hand pump",
    price: 27.99,
    sku: "FW-BALL-001",
    image:
      "https://plus.unsplash.com/premium_photo-1664536968018-47d6812aad88?w=600&h=600&fit=crop",
    category: "equipment",
    inStock: true,
    weight: 40,
    rating: 4.6,
    reviewCount: 73,
  },
  {
    id: "jump-rope",
    name: "Speed Jump Rope",
    slug: "speed-jump-rope",
    description:
      "Lightweight speed rope with ball-bearing handles for smooth rotation. Adjustable cable length fits any height. Perfect for warm-ups and cardio sessions.",
    shortDescription: "Ball-bearing handles, adjustable length",
    price: 16.99,
    sku: "FW-ROPE-001",
    image:
      "https://images.unsplash.com/photo-1514994667787-b48ca37155f0?w=600&h=600&fit=crop",
    category: "accessories",
    inStock: true,
    badge: "Best Seller",
    weight: 8,
    rating: 4.8,
    reviewCount: 215,
  },
  {
    id: "massage-ball",
    name: "Massage Ball Set",
    slug: "massage-ball-set",
    description:
      "Set of 3 therapy balls (firm, medium, soft) for targeted muscle relief. Ideal for plantar fascia, shoulders, and back. Compact and travel-friendly.",
    shortDescription: "3-pack firm/medium/soft for trigger points",
    price: 19.99,
    sku: "FW-MBALL-001",
    image:
      "https://images.unsplash.com/photo-1634892562163-3cf7253b88a8?w=600&h=600&fit=crop",
    category: "accessories",
    inStock: true,
    weight: 10,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "pilates-ring",
    name: "Pilates Ring",
    slug: "pilates-ring",
    description:
      "Dual-grip magic circle for Pilates resistance training. Flexible fiberglass ring with padded handles. Targets inner/outer thighs, arms, and chest.",
    shortDescription: "Dual-grip magic circle, padded handles",
    price: 32.99,
    sku: "FW-RING-001",
    image:
      "https://plus.unsplash.com/premium_photo-1753396306413-666ae0b49e59?w=600&h=600&fit=crop",
    category: "equipment",
    inStock: true,
    badge: "Sale",
    weight: 14,
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "grip-socks",
    name: "Grip Socks (3-Pack)",
    slug: "grip-socks-3-pack",
    description:
      "Non-slip grip socks designed for Pilates, barre, and yoga. Silicone treads on the sole prevent sliding. Breathable cotton blend. Unisex sizing.",
    shortDescription: "Non-slip silicone treads, breathable cotton",
    price: 21.99,
    sku: "FW-SOCK-001",
    image:
      "https://images.unsplash.com/photo-1640026199235-c24aa417b552?w=600&h=600&fit=crop",
    category: "apparel",
    inStock: true,
    weight: 4,
    rating: 4.8,
    reviewCount: 201,
  },
];
