import { PlanPackage } from "./types";

export const planPackages: PlanPackage[] = [
  {
    id: "drop-in",
    name: "Drop-in Class",
    description: "For those who want to try",
    classes: 1,
    duration: "30 days",
    price: 60,
    pricePerClass: 60,
  },
  {
    id: "pack-4",
    name: "4 Class Pack",
    description: "Ideal for beginners",
    classes: 4,
    duration: "30 days",
    price: 200,
    pricePerClass: 50,
    savings: 40,
  },
  {
    id: "monthly",
    name: "Monthly",
    description: "For regular practice",
    classes: 8,
    duration: "30 days",
    price: 350,
    pricePerClass: 43.75,
    popular: true,
    savings: 130,
  },
  {
    id: "quarterly",
    name: "Quarterly",
    description: "3-month commitment",
    classes: 24,
    duration: "90 days",
    price: 900,
    pricePerClass: 37.5,
    savings: 540,
  },
  {
    id: "annual",
    name: "Annual",
    description: "Best value",
    classes: 96,
    duration: "365 days",
    price: 2880,
    pricePerClass: 30,
    bestValue: true,
    savings: 2880,
  },
];
